package com.artknower.app.ui.screens

import android.Manifest
import android.content.Intent
import android.content.pm.PackageManager
import android.net.Uri
import android.os.Bundle
import android.speech.RecognitionListener
import android.speech.RecognizerIntent
import android.speech.SpeechRecognizer
import android.widget.Toast
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.ArrowBack
import androidx.compose.material.icons.filled.AutoAwesome
import androidx.compose.material.icons.filled.Mic
import androidx.compose.material.icons.filled.PhotoCamera
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.core.content.ContextCompat
import coil.compose.AsyncImage
import com.artknower.app.data.repository.SpeechRepository
import com.artknower.app.ui.theme.GrayText
import com.artknower.app.ui.theme.ThinBorderColor
import com.artknower.app.utils.AudioRecorderHelper
import kotlinx.coroutines.launch
import java.util.Locale

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun ArtisanStoryFormScreen(
    onBack: () -> Unit,
    onStorySubmitted: (name: String, location: String, craftType: String, storyText: String, imageUri: Uri?) -> Unit
) {
    val coroutineScope = rememberCoroutineScope()
    val context = LocalContext.current

    var name by remember { mutableStateOf("") }
    var location by remember { mutableStateOf("") }
    var craftType by remember { mutableStateOf("") }
    
    var storyText by remember { mutableStateOf("") }
    var isRecording by remember { mutableStateOf(false) }
    var isProcessingAi by remember { mutableStateOf(false) }
    
    var selectedImageUri by remember { mutableStateOf<Uri?>(null) }
    
    val speechRecognizer = remember { SpeechRecognizer.createSpeechRecognizer(context) }
    val audioRecorderHelper = remember { AudioRecorderHelper(context) }

    fun processAudioAndGenerate(audio: AudioRecorderHelper.RecordedAudio?, transcriptFallback: String) {
        isProcessingAi = true
        coroutineScope.launch {
            try {
                if (audio != null && audio.base64Data.isNotBlank()) {
                    val result = SpeechRepository.runVoiceCatalogPipeline(
                        audioBase64 = audio.base64Data,
                        audioEncoding = audio.encoding,
                        spokenLanguage = "hi",
                        sampleRateHertz = audio.sampleRateHertz,
                        autoStore = false
                    )

                    result.onSuccess { response ->
                        val englishDesc = response.generatedTranslations?.translations
                            ?.firstOrNull { it.languageCode == "en" }?.description
                        val localDesc = response.generatedTranslations?.translations
                            ?.firstOrNull { it.languageCode == response.detectedLanguage }?.description
                        val bestStory = englishDesc?.takeIf { it.isNotBlank() }
                            ?: localDesc?.takeIf { it.isNotBlank() }
                            ?: response.transcript

                        if (bestStory.isNotBlank()) {
                            storyText = bestStory
                        }

                        if (name.isBlank() && !response.extractedDraft?.nameCandidate.isNullOrBlank()) {
                            name = response.extractedDraft!!.nameCandidate!!
                        }

                        Toast.makeText(context, "Story generated by AI! You can review and edit below.", Toast.LENGTH_SHORT).show()
                    }.onFailure {
                        // If audio pipeline failed but we have transcript, try description generation fallback
                        if (transcriptFallback.isNotBlank()) {
                            val descResult = SpeechRepository.generateArtisanDescription(transcriptFallback, "hi")
                            descResult.onSuccess { descResp ->
                                if (descResp.englishDescription.isNotBlank()) {
                                    storyText = descResp.englishDescription
                                }
                                Toast.makeText(context, "Story generated! You can review and edit below.", Toast.LENGTH_SHORT).show()
                            }.onFailure {
                                Toast.makeText(context, "Unable to create your story right now. Please try again.", Toast.LENGTH_SHORT).show()
                            }
                        } else {
                            Toast.makeText(context, "Unable to create your story right now. Please try again.", Toast.LENGTH_SHORT).show()
                        }
                    }
                } else if (transcriptFallback.isNotBlank()) {
                    val descResult = SpeechRepository.generateArtisanDescription(transcriptFallback, "hi")
                    descResult.onSuccess { descResp ->
                        if (descResp.englishDescription.isNotBlank()) {
                            storyText = descResp.englishDescription
                        }
                        Toast.makeText(context, "Story generated! You can review and edit below.", Toast.LENGTH_SHORT).show()
                    }.onFailure {
                        Toast.makeText(context, "Unable to create your story right now. Please try again.", Toast.LENGTH_SHORT).show()
                    }
                } else {
                    Toast.makeText(context, "No speech heard. Please try speaking again.", Toast.LENGTH_SHORT).show()
                }
            } catch (_: Exception) {
                Toast.makeText(context, "Unable to create your story right now. Please try again.", Toast.LENGTH_SHORT).show()
            } finally {
                isProcessingAi = false
            }
        }
    }

    fun stopListeningAndProcess() {
        if (!isRecording) return
        isRecording = false
        try {
            speechRecognizer.stopListening()
        } catch (_: Exception) {}

        val audio = audioRecorderHelper.stopAndGetAudio()
        processAudioAndGenerate(audio, storyText)
    }

    fun startListening() {
        if (isProcessingAi) return

        val hasPermission = ContextCompat.checkSelfPermission(
            context,
            Manifest.permission.RECORD_AUDIO
        ) == PackageManager.PERMISSION_GRANTED

        if (!hasPermission) {
            return
        }

        // Start real audio recorder
        audioRecorderHelper.startRecording()

        // Also start speech recognizer for live recognition feedback
        if (SpeechRecognizer.isRecognitionAvailable(context)) {
            val intent = Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH).apply {
                putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL, RecognizerIntent.LANGUAGE_MODEL_FREE_FORM)
                putExtra(RecognizerIntent.EXTRA_LANGUAGE, Locale.getDefault())
                putExtra(RecognizerIntent.EXTRA_PARTIAL_RESULTS, true)
                putExtra(RecognizerIntent.EXTRA_SPEECH_INPUT_COMPLETE_SILENCE_LENGTH_MILLIS, 5000L)
                putExtra(RecognizerIntent.EXTRA_SPEECH_INPUT_POSSIBLY_COMPLETE_SILENCE_LENGTH_MILLIS, 5000L)
            }
            try {
                isRecording = true
                speechRecognizer.startListening(intent)
            } catch (e: Exception) {
                isRecording = true
            }
        } else {
            isRecording = true
        }
    }

    // Voice permissions launcher
    val permissionLauncher = rememberLauncherForActivityResult(
        contract = ActivityResultContracts.RequestPermission(),
        onResult = { isGranted ->
            if (isGranted) {
                startListening()
            } else {
                Toast.makeText(context, "Microphone permission is required to record speech", Toast.LENGTH_SHORT).show()
            }
        }
    )

    // Image Picker launcher
    val photoPickerLauncher = rememberLauncherForActivityResult(
        contract = ActivityResultContracts.PickVisualMedia(),
        onResult = { uri -> selectedImageUri = uri }
    )

    DisposableEffect(Unit) {
        val listener = object : RecognitionListener {
            override fun onReadyForSpeech(params: Bundle?) {}
            override fun onBeginningOfSpeech() {}
            override fun onRmsChanged(rmsdB: Float) {}
            override fun onBufferReceived(buffer: ByteArray?) {}
            override fun onEndOfSpeech() {
                // Do NOT stop audio recording on brief pauses. Let user finish their full story.
            }
            override fun onError(error: Int) {
                // If speech recognizer has a timeout or pause, restart it if user is still recording
                if (isRecording) {
                    try {
                        val intent = Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH).apply {
                            putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL, RecognizerIntent.LANGUAGE_MODEL_FREE_FORM)
                            putExtra(RecognizerIntent.EXTRA_LANGUAGE, Locale.getDefault())
                            putExtra(RecognizerIntent.EXTRA_PARTIAL_RESULTS, true)
                        }
                        speechRecognizer.startListening(intent)
                    } catch (_: Exception) {}
                }
            }
            override fun onResults(results: Bundle?) {
                val matches = results?.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION)
                if (!matches.isNullOrEmpty()) {
                    val text = matches[0]
                    storyText = if (storyText.isBlank()) text else "$storyText $text"
                }
                // If the user is still recording their story, restart listening for the next sentence
                if (isRecording) {
                    try {
                        val intent = Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH).apply {
                            putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL, RecognizerIntent.LANGUAGE_MODEL_FREE_FORM)
                            putExtra(RecognizerIntent.EXTRA_LANGUAGE, Locale.getDefault())
                            putExtra(RecognizerIntent.EXTRA_PARTIAL_RESULTS, true)
                        }
                        speechRecognizer.startListening(intent)
                    } catch (_: Exception) {}
                }
            }
            override fun onPartialResults(partialResults: Bundle?) {
                val matches = partialResults?.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION)
                if (!matches.isNullOrEmpty()) {
                    val text = matches[0]
                    if (storyText.isBlank()) {
                        storyText = text
                    }
                }
            }
            override fun onEvent(eventType: Int, params: Bundle?) {}
        }
        speechRecognizer.setRecognitionListener(listener)
        
        onDispose {
            try {
                speechRecognizer.stopListening()
                speechRecognizer.destroy()
            } catch (_: Exception) {}
            audioRecorderHelper.release()
        }
    }

    Column(
        modifier = Modifier
            .fillMaxSize()
            .background(MaterialTheme.colorScheme.background)
            .padding(24.dp)
            .verticalScroll(rememberScrollState()),
        horizontalAlignment = Alignment.Start
    ) {
        Row(verticalAlignment = Alignment.CenterVertically) {
            IconButton(onClick = onBack, modifier = Modifier.offset(x = (-12).dp)) {
                Icon(Icons.Default.ArrowBack, contentDescription = "Back", tint = MaterialTheme.colorScheme.primary)
            }
            Text(
                text = "Your Details",
                style = MaterialTheme.typography.headlineMedium,
                color = MaterialTheme.colorScheme.primary,
                fontWeight = FontWeight.Bold
            )
        }
        
        Spacer(modifier = Modifier.height(16.dp))

        OutlinedTextField(
            value = name,
            onValueChange = { name = it },
            label = { Text("Artisan Name") },
            modifier = Modifier.fillMaxWidth(),
            shape = RoundedCornerShape(12.dp),
            colors = OutlinedTextFieldDefaults.colors(
                focusedBorderColor = MaterialTheme.colorScheme.primary,
                unfocusedBorderColor = ThinBorderColor
            )
        )
        
        Spacer(modifier = Modifier.height(8.dp))
        
        OutlinedTextField(
            value = location,
            onValueChange = { location = it },
            label = { Text("Location (Village, State)") },
            modifier = Modifier.fillMaxWidth(),
            shape = RoundedCornerShape(12.dp),
            colors = OutlinedTextFieldDefaults.colors(
                focusedBorderColor = MaterialTheme.colorScheme.primary,
                unfocusedBorderColor = ThinBorderColor
            )
        )
        
        Spacer(modifier = Modifier.height(8.dp))
        
        OutlinedTextField(
            value = craftType,
            onValueChange = { craftType = it },
            label = { Text("Craft Type (e.g., Pottery, Weaving)") },
            modifier = Modifier.fillMaxWidth(),
            shape = RoundedCornerShape(12.dp),
            colors = OutlinedTextFieldDefaults.colors(
                focusedBorderColor = MaterialTheme.colorScheme.primary,
                unfocusedBorderColor = ThinBorderColor
            )
        )
        
        Spacer(modifier = Modifier.height(32.dp))
        
        Text(
            text = "Tell Your Story",
            style = MaterialTheme.typography.titleLarge,
            color = MaterialTheme.colorScheme.primary,
            fontWeight = FontWeight.Bold
        )
        
        Text(
            text = "Share how you learned the craft, your journey, and the tradition behind it. Speak in Hindi, Marathi, or English.",
            style = MaterialTheme.typography.bodyMedium,
            color = GrayText
        )
        
        Spacer(modifier = Modifier.height(16.dp))
        
        Button(
            onClick = {
                if (isRecording) {
                    stopListeningAndProcess()
                } else if (!isProcessingAi) {
                    val hasPermission = ContextCompat.checkSelfPermission(
                        context,
                        Manifest.permission.RECORD_AUDIO
                    ) == PackageManager.PERMISSION_GRANTED

                    if (hasPermission) {
                        startListening()
                    } else {
                        permissionLauncher.launch(Manifest.permission.RECORD_AUDIO)
                    }
                }
            },
            enabled = !isProcessingAi,
            modifier = Modifier.fillMaxWidth().height(56.dp),
            shape = RoundedCornerShape(12.dp),
            colors = ButtonDefaults.buttonColors(
                containerColor = when {
                    isRecording -> MaterialTheme.colorScheme.error
                    isProcessingAi -> MaterialTheme.colorScheme.primary.copy(alpha = 0.7f)
                    else -> MaterialTheme.colorScheme.secondary
                },
                contentColor = when {
                    isRecording -> MaterialTheme.colorScheme.onError
                    else -> MaterialTheme.colorScheme.onSecondary
                }
            )
        ) {
            if (isProcessingAi) {
                CircularProgressIndicator(
                    modifier = Modifier.size(20.dp),
                    color = MaterialTheme.colorScheme.onPrimary,
                    strokeWidth = 2.dp
                )
                Spacer(modifier = Modifier.width(10.dp))
                Text(
                    text = "Creating your story...",
                    fontSize = 16.sp,
                    fontWeight = FontWeight.Bold
                )
            } else {
                Icon(Icons.Default.Mic, contentDescription = "Microphone")
                Spacer(modifier = Modifier.width(8.dp))
                Text(
                    text = if (isRecording) "Listening... Tap to Stop & Create Story" else "Tap to Speak Story",
                    fontSize = 16.sp,
                    fontWeight = FontWeight.Bold
                )
            }
        }
        
        Spacer(modifier = Modifier.height(16.dp))
        
        OutlinedTextField(
            value = storyText,
            onValueChange = { storyText = it },
            label = { Text("Your story will appear here. You can also edit it.") },
            modifier = Modifier.fillMaxWidth().height(160.dp),
            shape = RoundedCornerShape(12.dp),
            maxLines = 8,
            colors = OutlinedTextFieldDefaults.colors(
                focusedBorderColor = MaterialTheme.colorScheme.primary,
                unfocusedBorderColor = ThinBorderColor
            )
        )

        if (storyText.isNotBlank() && !isProcessingAi && !isRecording) {
            Spacer(modifier = Modifier.height(8.dp))
            OutlinedButton(
                onClick = {
                    isProcessingAi = true
                    coroutineScope.launch {
                        try {
                            val descResult = SpeechRepository.generateArtisanDescription(storyText, "hi")
                            descResult.onSuccess { descResp ->
                                if (descResp.englishDescription.isNotBlank()) {
                                    storyText = descResp.englishDescription
                                }
                                Toast.makeText(context, "Story polished with AI!", Toast.LENGTH_SHORT).show()
                            }.onFailure {
                                Toast.makeText(context, "Unable to create your story right now. Please try again.", Toast.LENGTH_SHORT).show()
                            }
                        } finally {
                            isProcessingAi = false
                        }
                    }
                },
                modifier = Modifier.align(Alignment.End),
                shape = RoundedCornerShape(8.dp)
            ) {
                Icon(Icons.Default.AutoAwesome, contentDescription = null, modifier = Modifier.size(16.dp))
                Spacer(modifier = Modifier.width(6.dp))
                Text("Polish with AI", fontSize = 13.sp)
            }
        }

        Spacer(modifier = Modifier.height(24.dp))
        
        Text(
            text = "Upload Craft Image",
            style = MaterialTheme.typography.titleLarge,
            color = MaterialTheme.colorScheme.primary,
            fontWeight = FontWeight.Bold
        )
        
        Spacer(modifier = Modifier.height(16.dp))
        
        Button(
            onClick = { 
                photoPickerLauncher.launch(androidx.activity.result.PickVisualMediaRequest(ActivityResultContracts.PickVisualMedia.ImageOnly))
            },
            modifier = Modifier.fillMaxWidth().height(56.dp),
            shape = RoundedCornerShape(12.dp),
            colors = ButtonDefaults.buttonColors(containerColor = MaterialTheme.colorScheme.surface),
            elevation = ButtonDefaults.buttonElevation(defaultElevation = 2.dp)
        ) {
            Icon(Icons.Default.PhotoCamera, contentDescription = "Camera", tint = MaterialTheme.colorScheme.primary)
            Spacer(modifier = Modifier.width(8.dp))
            Text("Select Image", color = MaterialTheme.colorScheme.primary, fontSize = 16.sp, fontWeight = FontWeight.SemiBold)
        }
        
        if (selectedImageUri != null) {
            Spacer(modifier = Modifier.height(16.dp))
            AsyncImage(
                model = selectedImageUri,
                contentDescription = "Selected Craft",
                modifier = Modifier
                    .fillMaxWidth()
                    .height(200.dp),
                contentScale = ContentScale.Crop
            )
        }

        Spacer(modifier = Modifier.height(40.dp))
        
        Button(
            onClick = {
                onStorySubmitted(name, location, craftType, storyText, selectedImageUri)
            },
            enabled = !isProcessingAi && !isRecording,
            modifier = Modifier.fillMaxWidth().height(56.dp),
            shape = RoundedCornerShape(12.dp),
            colors = ButtonDefaults.buttonColors(containerColor = MaterialTheme.colorScheme.primary)
        ) {
            Text(
                text = "Preview Article",
                fontSize = 18.sp,
                fontWeight = FontWeight.Bold,
                color = MaterialTheme.colorScheme.onPrimary
            )
        }
        
        Spacer(modifier = Modifier.height(24.dp))
    }
}
